server:
  port: 7000

spring:
  banner:
    location: classpath:banner/banner.txt
    image:
     location: classpath:fotocreador/microservicios.png
  application:
    name: config-server
  cloud:
    config:
      server:
         git:
          default-label: master
          uri: git@github.com:Hackathon-ChatGPT-NTTDATA/configserver.git
          #uri: https://github.com/NTTData-Bootcamp-Microservicios/semana4-config-server
          search-paths: config-data
      
          
