spring:
  cloud:
    gateway:
      routes[0]:
        id: alumno
        predicates: Path=/api/alumno/**
        filters: StripPrefix=2
        uri: lb://alumno
 
      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
  
