spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://119.8.148.191:4200' 
            allowedHeaders:
              - Content-Type
            allowedCredentials: false
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              
      routes[0]:
        id: alumno
        predicates: Path=/api/alumno/**
        filters: StripPrefix=2
        uri: lb://alumno
      routes[1]:
        id: singularidad
        predicates: Path=/api/singularidad/**
        filters: StripPrefix=2
        uri: lb://singularidad
      routes[2]:
        id: cursos
        predicates: Path=/api/cursos/**
        filters: StripPrefix=2
        uri: lb://cursos
      routes[3]:
        id: examenes
        predicates: Path=/api/examenes/**
        filters: StripPrefix=2
        uri: lb://examenes
      routes[4]:
        id: preguntas
        predicates: Path=/api/preguntas/**
        filters: StripPrefix=2
        uri: lb://preguntas
      routes[5]:
        id: respuestas
        predicates: Path=/api/respuestas/**
        filters: StripPrefix=2
        uri: lb://respuestas

        
      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: http://119.8.148.191
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://119.8.148.191:8761/eureka
  
